### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by mihlav** [amitfin/oref_alert#6]
### System Health details

Version | core-2022.6.0
Installation Type | Home Assistant Core
Development | false
Supervisor | false
Docker | false
User | homeassistant
Virtual Environment | true
Python Version | 3.9.2
Operating System Family | Linux
Operating System Version | 5.10.43
CPU Architecture | aarch64
Timezone | Asia/Jerusalem

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The integration fails with error 

### Reproduction steps

1. Install from HACS
2. Configur inegration
3.
...

### Debug logs

```text
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/oref_alert/__init__.py:11
Integration: oref_alert (documentation, issues)
First occurred: 8:15:30 PM (1 occurrences)
Last logged: 8:15:30 PM

Error setting up entry Oref Alert for oref_alert
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/oref_alert/__init__.py", line 11, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'
```

**Comment by amitfin** [comment]
The problem is compatibility with old version of Home Assistant. Your version is from June 2022, which is more than a year old. This integration is not compatible with your Home Assistant version. Please update Home Assistant first.
BTW, I'll add a check to make sure that such installations are blocked, so the error will be more straightforward. Thanks!

**Comment by amitfin** [comment]
Some more information:
1) Home Assistant deprecated the function `hass.config_entries.async_setup_platforms` and instead required all integrations to use `hass.config_entries.async_forward_entry_setups`. This is documented [here](https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/).
2) The new function `hass.config_entries.async_forward_entry_setups` is the one that is used by the "oref_alert" integration (as it should).
3) The new function was introduced by https://github.com/home-assistant/core/pull/73806 which got merged into `home-assistant:dev` on Jul 9, 2022. This means that the new function exists from Home Assistant 2022.8 (August release).
4) The Home Assistant where the problem occurred is 2022.6, and therefore the new function `hass.config_entries.async_forward_entry_setups` doesn't exist there.

I'll be adding a check that Home Assistant version is at least 2023.1 (which is 10 months old, and to reduce the chances of additional compatibility issues.)
